name: nebula-sync

secrets:
  primary:
    file: ./primary.txt
  replicas:
    file: ./replicas.txt

services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    environment:
      - PRIMARY_FILE=/run/secrets/primary
      - REPLICAS_FILE=/run/secrets/replicas
      - FULL_SYNC=true
      - CRON=* * * * *
    secrets:
      - primary
      - replicas
