name: audiobookshelf

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 2800:80
    volumes:
      - /safe/media/audiobooks:/audiobooks
      - /safe/media/podcasts:/podcasts
      - /safe/media/abs-metadata:/metadata
      - ./config:/config
    restart: unless-stopped
    user: 1000:1000
