name: pihole

networks:
  pihole-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.1.0/24

secrets:
  web-password:
    file: ./web-password.txt

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "2100:2100/tcp"
    environment:
      TZ: "Europe/Vienna"
      FTLCONF_dns_upstreams: "172.27.1.3#5053"
      FTLCONF_webserver_port: "2100"
      FTLCONF_dns_listeningMode: "all"
      FTLCONF_webserver_interface_boxed: "false"
      WEBPASSWORD_FILE: /run/secrets/web-password
    volumes:
      - ./pihole/pihole:/etc/pihole
      - ./pihole/dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
    networks:
      pihole-network:
        ipv4_address: 172.27.1.2
    secrets:
      - web-password

  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    ports:
      - "5053:53/tcp"
      - "5053:53/udp"
    volumes:
      - ./unbound:/opt/unbound/etc/unbound/
    restart: unless-stopped
    healthcheck:
      test: ["NONE"]
    networks:
      pihole-network:
        ipv4_address: 172.27.1.3
