name: glance-agent

secrets:
  glance-token:
    file: ./glance-token.txt

services:
  glance-agent:
    container_name: glance-agent
    image: glanceapp/agent
    environment:
      TOKEN_FILE: /run/secrets/glance-token
    ports:
      - 27973:27973
    restart: unless-stopped
    secrets:
      - glance-token
