name: beszel-hub

services:
  beszel-hub:
    image: henrygd/beszel
    container_name: beszel-hub
    restart: unless-stopped
    ports:
      - 3200:8090
    volumes:
      - ./beszel_data:/beszel_data
