name: beszel-agent

services:
  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./beszel_agent_data:/var/lib/beszel-agent
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      - ${DATA_DISK}/.beszel:/extra-filesystems/data-disk:ro
      - ${PARITY_DISK}/.beszel:/extra-filesystems/parity-disk:ro
    environment:
      LISTEN: 45876
      KEY: ${SSH_KEY}
      HUB_URL: "http://mainframe:3200"
      TOKEN: ${TOKEN}
