name: servarr

networks:
  servarr-network:
    name: servarr-network
    ipam:
      config:
        - subnet: 172.27.7.0/24

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=2701
      - TORRENTING_PORT=2700
    ports:
      - 2700:2700 # qbittorrent web interface
      - 2701:2701 # qbittorrent torrent port
    volumes:
      - ./qbittorrent:/config
      - /safe/media:/data
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.8

  jellyseerr:
   container_name: jellyseerr
   image: fallenbagel/jellyseerr:latest
   environment:
     - PUID=${PUID}
     - PGID=${PGID}
     - TZ=${TZ}
   volumes:
     - ./jellyseerr:/app/config
   ports:
     - 2702:5055
   networks:
     servarrnetwork:
       ipv4_address: 172.39.0.2
   restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./prowlarr:/config
    restart: unless-stopped
    ports:
      - 2703:9696
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.3

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./radarr:/config
      - /safe/media:/data
    ports:
      - 2704:7878
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.4

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./sonarr:/config
      - /safe/media:/data
    ports:
      - 2705:8989
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.5

  lidarr:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr:latest
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./lidarr:/config
      - /safe/media:/data
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 2706:8686
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.6

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./bazarr:/config
      - /safe/media:/data
    ports:
      - 2707:6767
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.7
