name: servarr

networks:
  servarr-network:
    name: servarr-network
    ipam:
      config:
        - subnet: 172.27.7.0/24

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=2701
      - TORRENTING_PORT=2700
    ports:
      - 2700:2700
      - 2701:2701
    volumes:
      - ./qbittorrent:/config
      - /mnt/media:/data
      - /home/jacko/downloads:/downloads
    networks:
      servarr-network:
        ipv4_address: 172.27.7.2

  jellyseerr:
   container_name: jellyseerr
   image: fallenbagel/jellyseerr:latest
   environment:
     - PUID=${PUID}
     - PGID=${PGID}
     - TZ=${TZ}
   volumes:
     - ./jellyseerr:/app/config
     - /home/jacko/downloads:/downloads
   ports:
     - 2702:5055
   networks:
     servarr-network:
       ipv4_address: 172.27.7.3
   restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./prowlarr:/config
      - /home/jacko/downloads:/downloads
    restart: unless-stopped
    ports:
      - 2703:9696
    networks:
      servarr-network:
        ipv4_address: 172.27.7.4

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./radarr:/config
      - /mnt/media:/data
      - /home/jacko/downloads:/downloads
    ports:
      - 2704:7878
    networks:
      servarr-network:
        ipv4_address: 172.27.7.5

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./sonarr:/config
      - /mnt/media:/data
      - /home/jacko/downloads:/downloads
    ports:
      - 2705:8989
    networks:
      servarr-network:
        ipv4_address: 172.27.7.6

  lidarr:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr:latest
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./lidarr:/config
      - /mnt/media:/data
      - /home/jacko/downloads:/downloads
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 2706:8686
    networks:
      servarr-network:
        ipv4_address: 172.27.7.7

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./bazarr:/config
      - /mnt/media:/data
      - /home/jacko/downloads:/downloads
    ports:
      - 2707:6767
    networks:
      servarr-network:
        ipv4_address: 172.27.7.8

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 2708:8191
    restart: unless-stopped 
    networks:
      servarr-network:
        ipv4_address: 172.27.7.9

  readarr:
    image: ghcr.io/pennydreadful/bookshelf:hardcover
    container_name: readarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 2709:8787
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./readarr:/config
      - /mnt/media:/data
      - /home/jacko/downloads:/downloads
    restart: unless-stopped 
    networks:
      servarr-network:
        ipv4_address: 172.27.7.10


  slskd:
    image: slskd/slskd:latest
    container_name: slskd
    user: 1000:1000
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SLSKD_REMOTE_CONFIGURATION=true
    ports:
      - 2710:5030/tcp
      - 50300:50300/tcp
    volumes:
      - /var/slskd:/app:rw
      - /mnt/media:/data
    restart: unless-stopped 
    networks:
      servarr-network:
        ipv4_address: 172.27.7.11
  #
  # audiobookrequest:
  #   image: markbeep/audiobookrequest:latest
  #   container_name: audiobookrequest
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #   ports:
  #     - 2710:8000
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - ./audiobookrequest:/config
  #   restart: unless-stopped 
  #   networks:
  #     servarr-network:
  #       ipv4_address: 172.27.7.11
