server:
  # assets-path: /app/assets
  port: ${PORT}
  proxied: true

pages:
  # It's not necessary to create a new file for each page and include it, you can simply
  # put its contents here, though multiple pages are easier to manage when separated
  - $include: neverlab.yml
