name: dockge

services:
  dockge:
    container_name: dockge
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      - 3100:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - ${STACKS_DIR}:${STACKS_DIR}
    environment:
      - DOCKGE_STACKS_DIR=${STACKS_DIR}
      - DOCKGE_ENABLE_CONSOLE=true
